title: Data Rescue Project Portal
description: Links to public data archived through combined efforts and coordinated by the Data Rescue Project.
url: https://portal.datarescueproject.org
logo: /assets/images/drp-brand-3.png
strict_front_matter: true

# Generated, tracked content lives together under content/.
collections_dir: content
collections:
  datasets:
    output: true
    permalink: /datasets/:path/
  organizations:
    output: true
    permalink: /offices/:path/
  dataset_categories:
    output: true
    permalink: /categories/:path/

defaults:
  - scope:
      path: ""
      type: dataset_categories
    values:
      layout: category
      load_app_bundle: true
  - scope:
      path: ""
      type: datasets
    values:
      layout: dataset
      category: Uncategorized
      organization: N/A
  - scope:
      path: ""
      type: organizations
    values:
      layout: organization
      load_app_bundle: true

navigation:
  - title: Datasets
    url: /datasets/
  - title: Offices
    url: /offices/
  - title: Categories
    url: /categories/
  - title: Status
    url: /status/

markdown: kramdown
kramdown:
  input: GFM

opengraph:
  enabled: true

plugins:
  - jekyll-github-metadata
  - jekyll-sitemap

exclude:
  - assets/js/src/
  - CONTRIBUTING.md
  - data/
  - Dockerfile
  - docker-compose.yml
  - docs/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules/
  - package.json
  - package-lock.json
  - README.md
  - requirements.txt
  - scripts/
  - vendor/
